import {ArrowUpRight,CheckCircle2,Clock3,Target,TrendingUp} from "lucide-react";
import {useEffect,useState} from "react";
import {Card,Badge} from "../components/ui";
import {DIMENSION_WORKFLOWS} from "../types";
import {getCurrentUserDashboard} from "../services/data";
type DashboardData=Awaited<ReturnType<typeof getCurrentUserDashboard>>;
export function Dashboard({onNavigate}:{onNavigate:(p:"baseline"|"commitments"|"weekly")=>void}){
 const[data,setData]=useState<DashboardData|null>(null);const[error,setError]=useState("");
 useEffect(()=>{getCurrentUserDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load dashboard."));},[]);
 const score=data?.average==null?"—":data.average.toFixed(1);const commitments=data?.commitments.length??0;const completed=data?.commitments.filter(c=>c.status==="complete").length??0;
 return <div className="space-y-6"><div className="overflow-hidden rounded-3xl bg-[#172B4D] p-7 text-white shadow-xl md:p-10"><div className="max-w-4xl"><Badge>HIGH-PERFORMANCE OPERATING FRAMEWORK</Badge><h1 className="mt-4 text-3xl font-bold tracking-tight md:text-5xl">Assess. Commit. Track. Review. Improve.</h1><p className="mt-4 max-w-2xl text-slate-300">A disciplined weekly operating rhythm across 12 dimensions, connecting self-assessment to evidence, commitments, scorecards and management review.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>onNavigate("weekly")} className="rounded-xl bg-[#F58220] px-5 py-3 font-bold hover:bg-[#D96D12]">Complete weekly scorecard <ArrowUpRight size={17} className="ml-2 inline"/></button><button onClick={()=>onNavigate("commitments")} className="rounded-xl border border-white/20 px-5 py-3 font-bold hover:bg-white/10">Open PICC</button></div></div></div>
 {error&&<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{error}</Card>}
 <div className="grid gap-4 md:grid-cols-4"><Card className="p-5"><TrendingUp size={20} className="text-[#F58220]"/><p className="mt-4 text-sm text-[#667085]">Current score</p><p className="text-2xl font-bold text-[#172B4D]">{score}<span className="ml-2 text-xs text-slate-400">/ 5.0</span></p></Card><Card className="p-5"><Target size={20} className="text-[#F58220]"/><p className="mt-4 text-sm text-[#667085]">Dimensions</p><p className="text-2xl font-bold text-[#172B4D]">12<span className="ml-2 text-xs text-slate-400">weekly</span></p></Card><Card className="p-5"><Clock3 size={20} className="text-[#F58220]"/><p className="mt-4 text-sm text-[#667085]">Commitments</p><p className="text-2xl font-bold text-[#172B4D]">{commitments}<span className="ml-2 text-xs text-slate-400">{completed} complete</span></p></Card><Card className="p-5"><CheckCircle2 size={20} className="text-[#F58220]"/><p className="mt-4 text-sm text-[#667085]">Current cycle</p><p className="text-sm font-bold text-[#172B4D] mt-2">{data?.cycle?data.cycle.week_start+" → "+data.cycle.week_end:"Loading"}</p></Card></div>
 <Card className="p-6"><h2 className="text-lg font-bold text-[#263238]">12-dimension operating rhythm</h2><p className="text-sm text-[#667085]">Each dimension follows Assess → Commit → Track → Review → Improve.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{DIMENSION_WORKFLOWS.map((d,i)=><div key={d.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center gap-3"><span className="text-xs font-bold text-[#F58220]">{String(i+1).padStart(2,"0")}</span><span className="font-semibold text-[#172B4D]">{d.name}</span></div><p className="mt-2 text-xs text-[#667085]">{d.weeklyPrompt}</p><div className="mt-3 flex flex-wrap gap-2">{d.scorecardMetrics.map(m=><span key={m} className="rounded-full bg-[#F4F6F8] px-2 py-1 text-[11px] text-[#667085]">{m}</span>)}</div></div>)}</div></Card></div>}