import {BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {useEffect,useMemo,useState} from "react";
import {Card} from "../components/ui";
import {DIMENSION_WORKFLOWS} from "../types";
import {getMyAssessments} from "../services/data";

type RangeKey="week"|"fortnight"|"month"|"quarter"|"halfYear";
const RANGES:[RangeKey,string][]=[["week","Weekly"],["fortnight","Fortnightly"],["month","Monthly"],["quarter","3 Months"],["halfYear","6 Months"]];

function bucketStart(date:string,key:RangeKey){const d=new Date(date+"T00:00:00");if(key==="week"){const day=d.getDay();d.setDate(d.getDate()-((day+6)%7))}else if(key==="fortnight"){const day=d.getDay();d.setDate(d.getDate()-((day+6)%7));const week=Math.floor((d.getTime()-new Date(1970,0,5).getTime())/(14*86400000));d.setDate(5+week*14)}else if(key==="month"){d.setDate(1)}else if(key==="quarter"){d.setMonth(Math.floor(d.getMonth()/3)*3,1)}else{d.setMonth(d.getMonth()-5,1)}return d.toISOString().slice(0,10)}

export function Trends(){const[data,setData]=useState<Awaited<ReturnType<typeof getMyAssessments>>>([]);const[error,setError]=useState("");const[range,setRange]=useState<RangeKey>("week");
useEffect(()=>{getMyAssessments(180).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load trends."));},[]);
const rows=useMemo(()=>{const cutoff=new Date();cutoff.setDate(cutoff.getDate()-(range==="week"?7:range==="fortnight"?14:range==="month"?31:range==="quarter"?92:184));const grouped=new Map<string,{sum:number,count:number}>();(data??[]).filter(a=>a.assessment_type==="weekly"&&new Date(a.period_start+"T00:00:00")>=cutoff).forEach(a=>{const scores=Array.isArray(a.scores)?a.scores:[];const rated=scores.filter((x:{score?:number})=>typeof x.score==="number"&&x.score>0);if(!rated.length)return;const key=bucketStart(a.period_start,range);const current=grouped.get(key)??{sum:0,count:0};current.sum+=rated.reduce((n:number,x:{score:number})=>n+x.score,0)/rated.length;current.count++;grouped.set(key,current)});return Array.from(grouped.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([period,v])=>({period,score:Number((v.sum/v.count).toFixed(2))}));},[data,range]);
const weekly=(data??[]).filter(a=>a.assessment_type==="weekly");const latest=weekly[0];const previous=weekly[1];const latestScores=Array.isArray(latest?.scores)?latest.scores:[];const previousScores=Array.isArray(previous?.scores)?previous.scores:[];
const movement=DIMENSION_WORKFLOWS.map(d=>{const a=latestScores.find((x:{dimensionId:string})=>x.dimensionId===d.id)?.score??0;const b=previousScores.find((x:{dimensionId:string})=>x.dimensionId===d.id)?.score??0;return{...d,score:a,delta:a-b};});
return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-[#172B4D]">Trend Analysis</h1><p className="mt-2 text-[#667085]">Review performance across weekly, fortnightly, monthly, 3-month and 6-month horizons.</p></div>{error&&<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}<Card className="p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-[#263238]">Performance trend</h2><p className="mt-1 text-xs text-[#667085]">Weekly assessments are consolidated into the selected reporting period.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="Trend period"><span className="sr-only">View:</span>{RANGES.map(([key,label])=><button key={key} type="button" onClick={()=>setRange(key)} aria-pressed={range===key} className={"rounded-xl border px-3 py-2 text-sm font-semibold transition "+(range===key?"border-[#0072CE] bg-[#0072CE] text-white":"border-slate-200 bg-white text-[#172B4D] hover:border-[#0072CE]")}>{label}</button>)}</div></div>{rows.length?<div className="mt-6 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period"/><YAxis domain={[0,5]}/><Tooltip/><Bar dataKey="score" fill="#F58220" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div>:<p className="mt-6 text-sm text-[#667085]">No weekly assessments are available for this period.</p>}</Card><Card className="p-6"><h2 className="font-bold text-[#263238]">Dimension movement</h2><p className="mt-1 text-xs text-[#667085]">Latest weekly assessment compared with the previous submitted week.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{movement.map(d=><div key={d.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-3"><span className="font-semibold text-[#172B4D]">{d.name}</span><span className="text-sm font-bold">{d.score?d.score.toFixed(1):"—"}</span></div><p className="mt-1 text-xs text-[#667085]">{d.delta>0?"Improving":d.delta<0?"Declining":"Stable"}{d.delta!==0?" ("+(d.delta>0?"+":"")+d.delta.toFixed(1)+")":""}</p></div>)}</div></Card></div>}