import {BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {useEffect,useState} from "react";
import {Card} from "../components/ui";
import {DIMENSION_WORKFLOWS} from "../types";
import {getCurrentUserDashboard} from "../services/data";
export function Trends(){const[data,setData]=useState<Awaited<ReturnType<typeof getCurrentUserDashboard>>|null>(null);const[error,setError]=useState("");
useEffect(()=>{getCurrentUserDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load trends."));},[]);
const rows=(data?.assessments??[]).filter(a=>a.assessment_type==="weekly").slice().reverse().map(a=>{const s=Array.isArray(a.scores)?a.scores:[];const r=s.filter((x:{score?:number})=>typeof x.score==="number"&&x.score>0);return{week:a.period_start,score:r.length?r.reduce((n:number,x:{score:number})=>n+x.score,0)/r.length:0};});
const weekly=(data?.assessments??[]).filter(a=>a.assessment_type==="weekly");const latest=weekly[0];const previous=weekly[1];const latestScores=Array.isArray(latest?.scores)?latest.scores:[];const previousScores=Array.isArray(previous?.scores)?previous.scores:[];
const movement=DIMENSION_WORKFLOWS.map(d=>{const a=latestScores.find((x:{dimensionId:string})=>x.dimensionId===d.id)?.score??0;const b=previousScores.find((x:{dimensionId:string})=>x.dimensionId===d.id)?.score??0;return{...d,score:a,delta:a-b};});
return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-[#172B4D]">Trend Analysis</h1><p className="mt-2 text-[#667085]">Track movement over time, recurring gaps and dimension-level improvement.</p></div>{error&&<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}<Card className="p-6"><h2 className="font-bold text-[#263238]">Overall weekly score trend</h2>{rows.length?<div className="mt-6 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="week"/><YAxis domain={[0,5]}/><Tooltip/><Bar dataKey="score" fill="#F58220" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div>:<p className="mt-6 text-sm text-[#667085]">No weekly assessments have been submitted yet.</p>}</Card><Card className="p-6"><h2 className="font-bold text-[#263238]">Dimension movement</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{movement.map(d=><div key={d.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between"><span className="font-semibold text-[#172B4D]">{d.name}</span><span className="text-sm font-bold">{d.score?d.score.toFixed(1):"—"}</span></div><p className="mt-1 text-xs text-[#667085]">{d.delta>0?"Improving":d.delta<0?"Declining":"Stable"}{d.delta!==0?" ("+(d.delta>0?"+":"")+d.delta.toFixed(1)+")":""}</p></div>)}</div></Card></div>}