export type WorkflowMetricKind="count"|"hours"|"percentage"|"score"|"text";
export type DimensionWorkflow={id:string;name:string;weeklyPrompt:string;piccPrompt:string;scorecardMetrics:string[];reviewFocus:string;consolidationFocus:string;trendFocus:string};
export type AssessmentScore={dimensionId:string;score:number;evidence:string};
export type Assessment={id:string;userId:string;type:"baseline"|"weekly";periodStart:string;periodEnd:string;scores:AssessmentScore[];submittedAt?:string};
export type Commitment={id:string;dimensionId:string;title:string;action:string;timeframe:string;evidence:string;status:"not_started"|"in_progress"|"complete"};
export type ScorecardEntry={id?:string;dimensionId:string;metrics:Record<string,number|string>;evidence:string};
export type Review={id:string;assessmentId:string;notes:string;barriers:string;support:string;reviewedAt:string};
export const DIMENSION_WORKFLOWS:DimensionWorkflow[]=[
{id:"accountability-ownership",name:"Accountability & Ownership",weeklyPrompt:"What did you own fully this week?",piccPrompt:"What will you own fully next week?",scorecardMetrics:["Proactive actions","Reactive actions"],reviewFocus:"Ownership gaps",consolidationFocus:"Accountability patterns",trendFocus:"Proactive ownership"},
{id:"innovation-improvement",name:"Innovation & Improvement",weeklyPrompt:"What process did you improve?",piccPrompt:"What improvement initiative will you lead?",scorecardMetrics:["Efficiency gain %"],reviewFocus:"Improvement opportunities",consolidationFocus:"Innovation themes",trendFocus:"Cumulative innovations"},
{id:"results-delivery",name:"Results Orientation & Delivery",weeklyPrompt:"How did timeliness and quality perform?",piccPrompt:"What delivery improvement will you make?",scorecardMetrics:["Deadlines met","Deadlines missed"],reviewFocus:"Recurring delivery issues",consolidationFocus:"Delivery patterns",trendFocus:"Delivery consistency"},
{id:"planning-prioritisation",name:"Planning & Prioritisation",weeklyPrompt:"How well did quarter → month → week → hour align?",piccPrompt:"What planning adjustment will you make?",scorecardMetrics:["Planned execution %","Actual execution %"],reviewFocus:"Planning alignment",consolidationFocus:"Systemic planning gaps",trendFocus:"Execution alignment"},
{id:"oversight-governance",name:"Oversight, Governance & Assurance",weeklyPrompt:"Update your oversight dashboard and assurance position.",piccPrompt:"How will you improve visibility?",scorecardMetrics:["Variances detected","Corrective actions"],reviewFocus:"Assurance confidence",consolidationFocus:"Governance themes",trendFocus:"Variance closure"},
{id:"focus-execution",name:"Focus & Execution Discipline",weeklyPrompt:"How effectively did you manage distraction and availability?",piccPrompt:"What focus discipline will you adopt?",scorecardMetrics:["Interruptions","Productive hours"],reviewFocus:"Execution discipline",consolidationFocus:"Focus patterns",trendFocus:"Discipline improvement"},
{id:"lessons-continuous-improvement",name:"Lessons Learned & Continuous Improvement",weeklyPrompt:"What lesson did you apply?",piccPrompt:"What lesson will you apply next week?",scorecardMetrics:["Lessons applied"],reviewFocus:"Applied learning",consolidationFocus:"Applied lessons",trendFocus:"Behavior change"},
{id:"decision-problem-solving",name:"Decision-Making & Problem Solving",weeklyPrompt:"How timely and effective were your decisions?",piccPrompt:"What proactive decision will you make?",scorecardMetrics:["Issues resolved","Issues escalated"],reviewFocus:"Problem-solving agility",consolidationFocus:"Decision patterns",trendFocus:"Resolution effectiveness"},
{id:"collaboration-teamwork",name:"Collaboration & Teamwork",weeklyPrompt:"How effective was cross-functional cooperation?",piccPrompt:"What collaborative action will you take?",scorecardMetrics:["Joint deliverables"],reviewFocus:"Team cooperation",consolidationFocus:"Team synergy",trendFocus:"Collaboration trends"},
{id:"communication-stakeholders",name:"Communication & Stakeholder Management",weeklyPrompt:"How clear and timely were communications and escalations?",piccPrompt:"What communication improvement will you make?",scorecardMetrics:["Stakeholder feedback score"],reviewFocus:"Communication gaps",consolidationFocus:"Stakeholder themes",trendFocus:"Communication effectiveness"},
{id:"client-engagement",name:"Client Engagement & Representation",weeklyPrompt:"How professional and effective were client interactions?",piccPrompt:"What client-facing improvement will you make?",scorecardMetrics:["Client satisfaction indicator"],reviewFocus:"Client representation",consolidationFocus:"Client outcomes",trendFocus:"Engagement outcomes"},
{id:"capability-skills",name:"Capability & Skills Development",weeklyPrompt:"How effectively did you apply and develop skills?",piccPrompt:"What skill enhancement will you pursue?",scorecardMetrics:["Training completed","Training applied"],reviewFocus:"Capability gaps",consolidationFocus:"Capability priorities",trendFocus:"Capability growth"}
];
export const FRAMEWORK_DIMENSIONS=DIMENSION_WORKFLOWS.map((d,i)=>({id:d.id,name:d.name,description:d.weeklyPrompt,weight:1/12,sortOrder:i+1}));