drop policy if exists assessments_lead_read on public.assessments;
drop policy if exists assessments_owner_select on public.assessments;
create policy assessments_read on public.assessments for select to authenticated using((select private.has_org_role(organization_id,array['manager','ceo','admin'])) or ((select auth.uid())=user_id and (select private.is_org_member(organization_id))));
drop policy if exists commitments_lead_read on public.commitments;
drop policy if exists commitments_owner_select on public.commitments;
create policy commitments_read on public.commitments for select to authenticated using((select private.has_org_role(organization_id,array['manager','ceo','admin'])) or ((select auth.uid())=user_id and (select private.is_org_member(organization_id))));
drop policy if exists scorecards_lead_read on public.scorecard_entries;
drop policy if exists scorecards_owner_select on public.scorecard_entries;
create policy scorecards_read on public.scorecard_entries for select to authenticated using((select private.has_org_role(organization_id,array['manager','ceo','admin'])) or ((select auth.uid())=user_id and (select private.is_org_member(organization_id))));
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using((select auth.uid())=id);
drop policy if exists memberships_self_read on public.organization_members;
create policy memberships_self_read on public.organization_members for select to authenticated using((select auth.uid())=user_id or (select private.has_org_role(organization_id,array['manager','ceo','admin'])));
drop policy if exists organizations_member_read on public.organizations;
create policy organizations_member_read on public.organizations for select to authenticated using((select private.is_org_member(id)));
drop policy if exists cycles_member_read on public.weekly_cycles;
create policy cycles_member_read on public.weekly_cycles for select to authenticated using((select private.is_org_member(organization_id)));
drop policy if exists audit_events_lead_read on public.audit_events;
create policy audit_events_lead_read on public.audit_events for select to authenticated using((select private.has_org_role(organization_id,array['manager','ceo','admin'])));
drop policy if exists audit_events_member_insert on public.audit_events;
create policy audit_events_member_insert on public.audit_events for insert to authenticated with check(user_id=(select auth.uid()) and (select private.is_org_member(organization_id)));
create index assessments_user_id_idx on public.assessments(user_id);
create index audit_events_user_id_idx on public.audit_events(user_id);
create index commitments_user_id_idx on public.commitments(user_id);
create index framework_dimensions_organization_id_idx on public.framework_dimensions(organization_id);
create index management_reviews_assessment_id_idx on public.management_reviews(assessment_id);
create index management_reviews_reviewer_id_idx on public.management_reviews(reviewer_id);
create index management_reviews_subject_user_id_idx on public.management_reviews(subject_user_id);
create index management_reviews_organization_id_idx on public.management_reviews(organization_id);
create index organization_members_user_id_idx on public.organization_members(user_id);
create index scorecard_entries_user_id_idx on public.scorecard_entries(user_id);
